apiVersion: v1
kind: ConfigMap
metadata:
  name: lms-backend-config
  namespace: lms
  labels:
    app: lms-backend
data:
  NODE_ENV: "production"
  PORT: "5000"
  FRONTEND_URL: "http://a95a4aa877dd34947b527b5dcca12486-ba3b48707382ddc0.elb.ap-south-1.amazonaws.com"
  AWS_REGION: "ap-south-1"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX: "100"
